### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by reillydonovan** [MohamadZeina/Disco_Diffusion_Local#43] opened 2022-11-26 04:43 UTC
When trying to run the notebook it cannot find the target web addresses to download.

[I 20:38:37.339 NotebookApp] Kernel started: b4edfb2b-3eb4-4509-bad4-88d8a9bab1e1, name: python3
--2022-11-25 20:38:48--  https://v-diffusion.s3.us-west-2.amazonaws.com/512x512_diffusion_uncond_finetune_008100.pt
Resolving v-diffusion.s3.us-west-2.amazonaws.com (v-diffusion.s3.us-west-2.amazonaws.com)... 52.218.240.185, 52.92.192.210, 52.92.128.146, ...
Connecting to v-diffusion.s3.us-west-2.amazonaws.com (v-diffusion.s3.us-west-2.amazonaws.com)|52.218.240.185|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-11-25 20:38:50 ERROR 404: Not Found.

--2022-11-25 20:38:50--  https://v-diffusion.s3.us-west-2.amazonaws.com/secondary_model_imagenet_2.pth
Resolving v-diffusion.s3.us-west-2.amazonaws.com (v-diffusion.s3.us-west-2.amazonaws.com)... 3.5.83.168, 52.92.192.210, 52.218.204.137, ...
Connecting to v-diffusion.s3.us-west-2.amazonaws.com (v-diffusion.s3.us-west-2.amazonaws.com)|3.5.83.168|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-11-25 20:38:51 ERROR 404: Not Found.

**Comment by juanpflores** [comment] 2022-11-26 20:51
I can confirm this issue. It looks like the AWS Bucket is no longer available. I got the model from this [link](https://www.reddit.com/r/DiscoDiffusion/comments/uh0qg8/secondary_model_imagenet_2pth_cant_find/) but I'm pretty sure this is not the latest model.

**Comment by juanpflores** [comment] 2022-11-26 20:56
Dupe of #25

**Comment by MohamadZeina** [comment] 2023-02-08 16:00
Thanks @juanpflores

**Closed as completed by MohamadZeina** 2023-02-08 16:00 UTC
